[workspace]
members = ["lib", "hostlib", "program", "script"]
resolver = "2"

[workspace.dependencies]
alloy-sol-types = "1"

[patch.crates-io]
p256 = { git = "https://github.com/sp1-patches/elliptic-curves", tag = "patch-p256-13.2-sp1-6.0.0" }
sha2 = { git = "https://github.com/sp1-patches/RustCrypto-hashes", package = "sha2", tag = "patch-sha2-0.10.9-sp1-6.0.0" }
