package org.nachweis.prover.prover

import android.content.Context
import uniffi.mopro.DerivedInputs
import uniffi.mopro.ProofResult
import uniffi.mopro.circuitDyadicSize
import uniffi.mopro.deriveInputs
import uniffi.mopro.prove
import uniffi.mopro.setupSrs
import uniffi.mopro.verify
import java.io.File

/**
 * Copies the bundled circuit and SRS into app storage once (Barretenberg reads
 * files, not asset streams) and drives `prover-mobile-core` through the
 * mopro/uniffi bindings (package uniffi.mopro, generated by scripts/build-rust.sh).
 */
class ProverService(private val context: Context) {
    data class Paths(val circuit: File, val vk: ByteArray, val vkHash: ByteArray, val g1: File)

    private val assetsToCopy = listOf("pid_sdjwt.json", "bn254_g1.dat")

    @Volatile
    private var paths: Paths? = null

    @Synchronized
    fun ensureAssets(): Paths {
        paths?.let { return it }
        val dir = File(context.filesDir, "prover").apply { mkdirs() }
        for (name in assetsToCopy) {
            val target = File(dir, name)
            val assetLen = context.assets.openFd(name).use { it.length }
            if (!target.exists() || target.length() != assetLen) {
                context.assets.open(name).use { input -> target.outputStream().use { input.copyTo(it, 1 shl 20) } }
            }
        }
        val vk = context.assets.open("pid_sdjwt_evm.vk").use { it.readBytes() }
        val vkHash = context.assets.open("pid_sdjwt_evm.vk_hash").use { it.readBytes() }
        return Paths(File(dir, "pid_sdjwt.json"), vk, vkHash, File(dir, "bn254_g1.dat")).also { paths = it }
    }

    /** Cheap call that loads the .so; a dlopen problem surfaces here instead of mid-flow. */
    fun dyadicSize(): UInt = circuitDyadicSize(ensureAssets().circuit.absolutePath)

    /**
     * Rust port of circuits/tools/gen-prover.ts against the bundled artifact's ABI
     * (bounds, witness order). Issuer key from the x5c leaf, aud = the pinned client_id.
     */
    fun derive(presentation: String, boundAddressHex: String, challengeHex: String): DerivedInputs =
        deriveInputs(ensureAssets().circuit.absolutePath, presentation, "", boundAddressHex, challengeHex, "")

    /** Loads the SRS into Barretenberg (idempotent); returns the point count (2^20 + 1). */
    fun loadSrs(): UInt {
        val p = ensureAssets()
        return setupSrs(p.circuit.absolutePath, p.g1.absolutePath)
    }

    /** Witness + UltraHonk keccak proof (`bb prove -t evm`) with the bundled desktop VK. */
    fun prove(witness: List<String>, lowMemory: Boolean): ProofResult {
        val p = ensureAssets()
        return prove(p.circuit.absolutePath, p.g1.absolutePath, p.vk, witness, true, lowMemory)
    }

    fun verify(proof: ByteArray, publicInputs: List<ByteArray>): Boolean = verify(proof, publicInputs, ensureAssets().vk, true)
}
